version: '*'

settings: |
  # Information about the namespace.
  information:
    # Organisational information.
    division: "IT"
    team: "Platform Architecture"
    projectName: "Backstage"
    projectLead: "Full Name"
    # The priority of the workload. Can be critical or medium.
    priority: "medium"
    technicalLead: "Full Name"
    # The Jira ticket ID of the Epic used to onboard the project.
    onboardingEpic: "N/A"
    # The link to the authority to operate.
    authorityToOperate: "N/A"

    # Information about tooling.
    gitGroupURL: "gccloudone-aurora"

    # Financial and organizational identifiers.
    FRC: 00001
    PE: 0001
    workloadID: 000001
    productID: 0001

  # Configurations about the namespace.
  namespace:
    # Extra labels to add to the namespace.
    labels: {}
    # The type of namespace.
    # Can be one of [gateway, solution, system].
    type: "solution"

  # Network policy configurations.
  netpol:
    allowSameNamespace: true

  # Policy configurations on the namespace.
  policies:
    # List of host/path that can be exposed from the namespace.
    allowedHosts: []

    # Boolean which defines if the namespace should have Istio injection.
    istioInjection: true

    # Refer to https://kubernetes.io/docs/concepts/security/pod-security-admission/
    # podSecurityAdmission:
    #   enforce:
    #     level: baseline
    #     version: v1.27
    #   audit:
    #     level: baseline
    #     version: v1.27
    #   warn:
    #     level: baseline
    #     version: v1.27

  # Defines the access control on the namespace.
  # Roles will be assigned based on the namespace type.
  rbac:
    groups:
      # Azure AD Group for Platform Architecture
      - "9999999-9999-9999-9999-999999999999"

  # Defines resource quotas on the namespace.
  resourceQuotas:
    # The maximum number of pods that can be in the namespace.
    pods: 60
    # Quotas related to services and external traffic.
    services:
      # The maximum number of loadbalancers that can be configured.
      loadbalancers: 0
      # The maximum number of NodePorts that can be configured.
      nodeports: 0
    # The upper limit of storage that can be requested across all persistent volumes.
    # Expects a string value of a number with or without units (uses SI units).
    storage: '0Gi'

  # Defines resources to be created in the namespace.
    # Defines resources to be created in the namespace.
  raw:
    resources: []

  # Defines cluster specific resources to be created in the namespace
  # Can be one of [aadPodIdentities].
  clusters:
    aur-prod-cc-00-aks: {}
